services:
  django:
    container_name      : django
    build: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name      : nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - django

  db:
    image: postgres:17.5
    container_name: postgresql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ProGATE4623!
      POSTGRES_DB: local_postgredb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d local_postgredb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  static_volume: